version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  sboot-posterr:
    image: sboot-posterr:staging
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - PROFILE_ACTIVE=production
      - POSTGRES_HOST=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PAGINATION_RANGE=5
volumes:
  db:
    driver: local